apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: azuredemosrepo/aks-lab-website:latest
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        volumeMounts:
        - name: jsonconfig-volume
          mountPath: /app/Configs/Environments/Kubernetes/Json
          readOnly: true
        - name: secrets-volume
          mountPath: /app/Configs/Environments/Kubernetes/Secrets
          readOnly: true
      volumes:
      - name: jsonconfig-volume
        configMap:
          name: config-json-website
      - name: secrets-volume
        secret:
          secretName: website-secret