apiVersion: v1
kind: Service
metadata:
  name: middle-service
spec:
  selector:
    app: middle-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: middle-service-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: middle-service
    spec:
      containers:
      - name: middle-service
        image: azuredemosrepo/aks-lab-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "200m"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        - name: "NameofThisService"
          value: "middle-service"
        - name: "DownStreamAPIName"
          value: "backend-service"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: backend-service-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: backend-service
    spec:
      containers:
      - name: backend-service
        image: azuredemosrepo/aks-lab-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "250Mi"
            cpu: "100m"
          limits:
            memory: "350Mi"
            cpu: "200m"
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Kubernetes"
        - name: "NameofThisService"
          value: "backend-service"