parameters:
  name: ''
  imageRepository: ''
  dir: ''
  artifactName: ''
  artifactPath: ''

jobs:  
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }} job
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: docker login -u $(registryUser) -p $(registryPassword) $(containerRegistry)
      displayName: 'docker login'
    - script: docker build -t $(containerRegistry)/${{ parameters.imageRepository }}:$(tag) -f ${{ parameters.dir }}/Dockerfile.ci ${{ parameters.dir }}
      displayName: 'docker build'
    - script: docker push $(containerRegistry)/${{ parameters.imageRepository }}:$(tag)
      displayName: 'docker push'
          
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: ${{ parameters.artifactName }}
        targetPath: ${{ parameters.artifactPath }}