parameters:
  name: ''
  imageRepository: ''
  dockerfilePath: ''
  artifactName: ''
  artifactPath: ''

jobs:  
  - job: ${{ parameters.name }}
    displayName: ${{ parameters.name }} job
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(dockerRegistryServiceConnection)
    - task: Docker@2
      displayName: Build and push image to container registry
      inputs:
        command: buildAndPush
        repository: ${{ parameters.imageRepository }}
        dockerfile: ${{ parameters.dockerfilePath }}
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          latest
          
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: ${{ parameters.artifactName }}
        targetPath: ${{ parameters.artifactPath }}

  