apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: #{registrylocation}#/website:#{Build.BuildNumber}#
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "#{EnvironmentName}#"
        volumeMounts:
        - name: jsonconfig-volume
          mountPath: /app/Configs/Environments/#{EnvironmentName}#/Json
          readOnly: true
        - name: xmlconfig-volume
          mountPath: /app/Configs/Environments/#{EnvironmentName}#/XML
          readOnly: true
        - name: secrets-volume
          mountPath: /app/Configs/Environments/#{EnvironmentName}#/Secrets
          readOnly: true
      volumes:
      - name: jsonconfig-volume
        configMap:
          name: config-json-website
      - name: xmlconfig-volume
        configMap:
          name: config-xml-website
      - name: secrets-volume
        secret:
          secretName: website-secret
      imagePullSecrets:
      - name: acr-auth