apiVersion: v1
kind: Service
metadata:
  name: website
spec:
  selector:
    app: website
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: website-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: stevesacr.azurecr.io/website:latest
        ports:
        - containerPort: 80
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "#{EnvironmentName}#"
        volumeMounts:
        - name: jsonconfig-volume
          mountPath: /app/config1
          readOnly: true
        - name: xmlconfig-volume
          mountPath: /app/config2
          readOnly: true
        - name: secrets-volume
          mountPath: /app/secrets
          readOnly: true
      volumes:
      - name: jsonconfig-volume
        configMap:
          name: config-json-website
      - name: xmlconfig-volume
        configMap:
          name: config-xml-website
      - name: secrets-volume
        secret:
          secretName: front-end-secret