FROM microsoft/dotnet:2.1-sdk as build
WORKDIR /app
 
COPY *.csproj .
RUN dotnet restore
 
COPY . .
RUN dotnet publish --output /out/ --configuration Release
 
FROM microsoft/dotnet:2.1-aspnetcore-runtime
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY --from=build /out .
ENTRYPOINT ["dotnet", "AKSWebsite.dll"]
