apiVersion: v1
kind: ServiceAccount
metadata:
  name: read-cluster-api-service-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-cluster-api-role
rules:
- apiGroups: [""]
  resources: ["deployments", "namespaces", "pods", "services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: read-cluster-api-binding
subjects:
  - kind: ServiceAccount
    name: read-cluster-api-service-account
    namespace: demo # This value needs to be in the YAML, therefore it will be a placed dynamically in DevOps Pipeline per environment
roleRef:
  kind: ClusterRole
  name: read-cluster-api-role
  apiGroup: rbac.authorization.k8s.io