version: '3.4'

services:
  akswebsite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  aksapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

