version: '3.4'

services:
  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5003:80"

  middle-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NameofThisService=Middle API
      - DownStreamAPIName=backend-api
    ports:
      - "5004:80"

  backend-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - NameofThisService=Backend API
    ports:
      - "5005:80"