version: '3.4'

services:
  website:
    image: website
    build:
      context: .
      dockerfile: AKSWebsite/Dockerfile

  api:
    image: api
    build:
      context: .
      dockerfile: AKSAPI/Dockerfile
