version: '3.4'

services:
  akswebsite:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DEMO_AKS_API_SERVICE_HOST=aksapi
      - DEMO_AKS_API_SERVICE_PORT=80
    ports:
      - "5003:80"

  aksapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"
