version: '3.4'

services:
  website:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DEMO_AKS_API_SERVICE_HOST=api
      - DEMO_AKS_API_SERVICE_PORT=80
    ports:
      - "5003:80"

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5004:80"
