version: '3.4'

services:
  akswebsite:
    image: ${DOCKER_REGISTRY}akswebsite
    build:
      context: .
      dockerfile: AKSWebsite/Dockerfile

  aksapi:
    image: ${DOCKER_REGISTRY}aksapi
    build:
      context: .
      dockerfile: AKSAPI/Dockerfile
